# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f268973717224dcd871b273b1dcea521087c9b7961b808a4ec143ac2fc84d7eddd59fd7f1ebdc8ebdb86f61d76df8a545168f45154606766f8ac7d49d93aa85

test:
  secret_key_base: 72de454aadeded03aae75e49db1ea1c51324dba983953800d81a45ca7249893015eb0568fbf70dfb230e003b61892d73df17920cc986fc46102afdff07972a53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
