source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'rails-api'
gem 'pg'
gem 'active_model_serializers', '0.10.0.rc1'
gem "rack-cors", require: "rack/cors"

group :development, :test do
  # Call 'binding.pry' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pry-stack_explorer'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
